# Generated by Django 4.1.1 on 2022-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter application category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the application', max_length=200)),
                ('summary', models.CharField(help_text='Enter a brief description of the application', max_length=1000)),
                ('category', models.ManyToManyField(help_text='Choose a category for the application', to='catalog.category')),
            ],
        ),
    ]
